### ISSUE TITLE
Boolean type in DB2

### ISSUE THREAD

**Issue by sebCIL** [BWICompanies/db2-driver#10]
**Describe the bug**
The boolean type in DB2 seems not to work. 
We have a "null" value instead of "true" / "false". 

**To Reproduce**
Create a boolean type in DB2. In PHP, make a select * from the table.

**Expected behavior**
true / false value

**Comment by alanseiden** [comment]
@sebCIL That's with this Laravel component? 
Please post a code sample and tell us what version of PHP you are using.

**Comment by sebCIL** [comment]
Hello,
After trying a few more times, it seems to work.
Obviously, I had done something wrong.
Sorry for the inconvenience !
