### ISSUE TITLE
Add support for Laravel 10

### ISSUE THREAD

**Issue by charalambosv** [BWICompanies/db2-driver#3]
Error when trying to install with Laravel 10
- Root composer.json requires bwicompanies/db2-driver 1.0.5 -> satisfiable by bwicompanies/db2-driver[1.0.5].
- bwicompanies/db2-driver 1.0.5 requires illuminate/contracts ^8|^9 -> found illuminate/contracts[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.2] but these were not loaded, likely because it conflicts with another require.

Any plans to add support for Laravel 10?

**Comment by TimoKarvinenSolteq** [comment]
I second this request.

**Comment by alanseiden** [comment]
@bennettblack What do you think? Do you plan to test with Laravel 10 soon or have access to the Laravel 10 unit tests?

**Comment by TimoKarvinenSolteq** [comment]
I actually got it to work with Laravel 10 with a local copy and minor changes. I was trying out Laravel Passport and with adding UUID (other thread) I got it to work.

**Comment by bennettblack** [comment]
@alanseiden Yes - planning to test with L10 and PHP 8.2

**Comment by alanseiden** [comment]
Thanks, Bennett!

**Comment by djordje47** [comment]
Hi everyone,

has anyone encountered this kind of issue:

![image](https://github.com/BWICompanies/db2-driver/assets/16069373/bb7ec342-6a42-4710-8092-a6db70a7ce74)

I have been struggling for days with this, I have changed the config file and tried all sorts of things. But I can't wrap my head around it. 

SQLSTATE[HYT00] SQLDriverConnect: 30189 [IBM][System i Access ODBC Driver]Connection login timed out.

Also, I created a simple script in vanilla php that works with the plain PDO. 

Would you happen to have any advice on solving this? 

Many thanks for considering my request.
