### ISSUE TITLE
Uuid type for DB2SchemaGrammar

### ISSUE THREAD

**Issue by TimoKarvinenSolteq** [BWICompanies/db2-driver#4]
Added this:
`    protected function typeUuid(Fluent $column)
    {
        return 'char(36)';
    }
`
to DB2SchemaGrammar.php
So I could get
`php artisan passport:install --uuids`
to work.

**Comment by TimoKarvinenSolteq** [comment]
To explain this a bit more. To succesfully install Laravel Passport in uuid -mode the database model has to have uuid type (which is just char(36). The above function was copied from MySQL version to this.

**Comment by bennettblack** [comment]
Thank you @TimoKarvinenSolteq - I'll get this in.
